# .github/workflows/main.yml
name: 'Tests'

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
#  schedule:
#    - cron: '5 5 * * 5'
    
jobs:
  unit-testing-iOS: 
    runs-on: macos-14
    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
    - name: Select Xcode 15.4
      run: sudo xcode-select -s "/Applications/Xcode_15.4.app"
    - name: Show xcodebuild version
      run: xcodebuild -version
    - name: Show xcode embedded SDKs
      run: xcodebuild -showsdks
    - name: Show buildable schemes
      run: xcodebuild -list
    - uses: mxcl/xcodebuild@v1.9.2
      with:
        platform: iOS
        scheme: 'XcodeTemplateProject'
        action: test
        code-coverage: true
        verbosity: xcpretty
        upload-logs: always
  
  unit-testing-macOS: 
    runs-on: macos-14
    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
    - name: Select Xcode 15.4
      run: sudo xcode-select -s "/Applications/Xcode_15.4.app"
    - name: Show xcodebuild version
      run: xcodebuild -version
    - name: Show xcode embedded SDKs
      run: xcodebuild -showsdks
    - name: Show buildable schemes
      run: xcodebuild -list
    - uses: mxcl/xcodebuild@v1.9.2
      with:
        platform: macOS
        scheme: 'XcodeTemplateProject'
        action: test
        code-coverage: true
        verbosity: xcpretty
        upload-logs: always
        
